refactor(statistic): refactor statistic and countdown to typescript
vueComponent/ant-design-vue pull request #2950
Opened 2020-10-09 07:47 UTC by ununian

First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [x] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
> 2. Resolve what problem.
> 3. Related issue link.

### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

2020-10-09 11:23 UTC, Amour1688 commented on components/statistic/Countdown.tsx
> +    let countdownId: number | undefined = undefined;
`countdownId` 不是响应式的

2020-10-09 11:23 UTC, Amour1688 commented on components/statistic/Countdown.tsx
> +    const { format } = props;
在这里不能解构

2020-10-09 14:10 UTC, ununian commented on components/statistic/Countdown.tsx
> +    let countdownId: number | undefined = undefined;
这个不需要是响应式的，不会用到模板里面，只是控制定时器的

2020-10-10 01:56 UTC, Amour1688 commented on components/statistic/Statistic.tsx
> +    const suffix = getComponentFromSetup(props, slots, 'suffix') as VNodeTypes;
这些变量的值不会随着属性不变化

2020-10-10 02:04 UTC, ununian commented on components/statistic/Statistic.tsx
> +    const suffix = getComponentFromSetup(props, slots, 'suffix') as VNodeTypes;
这个应该用计算属性么？

2020-10-13 07:30 UTC, tangjinzhou requested changes

2020-10-13 07:30 UTC, tangjinzhou commented on components/statistic/Countdown.tsx
> +        key={renderKey.value}
不要用key，会导致子元素全部重新 render
如果要使用composition api  试试  data-key={renderKey.value}

2020-10-13 07:30 UTC, tangjinzhou commented on components/statistic/Statistic.tsx
> +  decimalSeparator: { type: String, default: '.' },
缺少 format、onFinish

2020-10-13 07:30 UTC, tangjinzhou commented on components/statistic/Statistic.tsx
> +  prefix: { type: String },
prefix: PropTypes.VNodeChild

2020-10-13 07:37 UTC, Amour1688 commented on components/statistic/Statistic.tsx
> +  title: { type: String },
`props` 的声明尽量参考一下已经改完的组件吧，不要单独搞一套风格

2020-10-13 07:50 UTC, ununian commented on components/statistic/Statistic.tsx
> +  title: { type: String },
嗯 ，我写的时候还没几个合并了的pr，所以不知道怎么写props

2020-10-13 08:08 UTC, ununian commented on components/statistic/Statistic.tsx
> +  decimalSeparator: { type: String, default: '.' },
这2个不是 CountDown 才有的吗？ 我就没写在 Statistic 里面了

2020-10-13 09:09 UTC, Amour1688 commented on components/statistic/Number.tsx
> +const StatisticNumber = (
这里可以用 `FunctionalComponent`

2020-10-13 09:16 UTC, Amour1688 commented on components/statistic/Number.tsx
> +const StatisticNumber = (
函数式组件还是需要声明 `props` 的

2020-10-13 13:35 UTC, ununian commented on components/statistic/Number.tsx
> +const StatisticNumber = (
这里我测试了一下，如果不设置函数式组件的props，那么会把所有的attrs塞入 props，相当于 props 和 attrs 是等价的。
这里这样写 tsx 能正确识别所需的 props。如果用 attrs 的话，tsx 就不能正确识别。
和 react的高阶函数式组件很像。虽然我没在vue3的文档里面找到相关的描述。
我写的时候是参考了 RenderEmpty 的代码。

2020-10-13 13:38 UTC, Amour1688 commented on components/statistic/Number.tsx
> +const StatisticNumber = (
不设置 props 在 `sfc` 会有问题

2020-10-15 12:35 UTC, Amour1688 commented
冲突解决一下吧

2020-10-16 09:06 UTC, ununian commented
我先整理一下

2020-10-16 09:08 UTC, closed without merging