fix: declare Tree Component type
vueComponent/ant-design-vue pull request #3178
Opened 2020-11-14 16:38 UTC by ajuner

First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [x] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### Changelog description (Optional if not new feature)

这个tree组件花了挺长时间看的，之前没敢动因为缺失挺多类型的，然后发现了DirectoryTree.tsx文件中lastSelectedKey的默认值是空数组导致类型判断出了问题，在组件中其他位置用法都是string就默认给了个空字符串，这里做了一个小改动，然后添加了一些interface来给这几个组件做声明，字段是按文档给来声明的，如果有缺失或者错误的请指出~~

2020-11-15 08:12 UTC, Amour1688 commented on components/tree/util.ts
> +  console.log(rootChildren)
lint 挂了

2020-11-17 13:27 UTC, tangjinzhou requested changes

2020-11-17 14:31 UTC, ajuner commented
居然全都是可选的。。

2020-11-17 14:49 UTC, Amour1688 commented on components/tree/Tree.tsx
> +  scopedSlots?: any;
没有 `scopedSlots` 这个属性了吧

2020-11-17 14:53 UTC, ajuner commented on components/tree/Tree.tsx
> +  scopedSlots?: any;
看逻辑上这个属性还是在的，文档上是没了  我给他去掉

2020-11-17 15:14 UTC, Amour1688 commented
可以把 props 里面 treeData 的类型也定义一下

2020-11-17 15:18 UTC, ajuner commented
> 可以把 props 里面 treeData 的类型也定义一下

嗯嗯

2020-11-17 15:57 UTC, ajuner commented
treeData下的children做类型递归有点问题。。

2020-11-18 09:37 UTC, merged