fix: carousel's pauseOnDotsHover not work
vueComponent/ant-design-vue pull request #3519
Opened 2021-01-11 09:11 UTC by snowtreetree

### This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Use Carousel, set autoplay, autoplaySpeed, pauseOnDotsHover.
> 2. Hover on dots, it doesn't work.

### API Realization (Optional if not new feature)

> 1.  show file changes.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. fix Carousel's prop of pauseOnDotsHover not work.
> 2. 修复Carousel组件pauseOnDotsHover失效问题。

### Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

2021-01-12 03:07 UTC, ajuner commented
确认一下吧，试了一下pauseOnDotsHover是生效的

2021-01-12 03:35 UTC, snowtreetree commented
https://codesandbox.io/s/adoring-butterfly-1jxji?file=/src/App.vue
@ajuner

2021-01-12 03:40 UTC, snowtreetree commented
https://user-images.githubusercontent.com/30932683/104266611-ec543280-54ca-11eb-8433-caf24b2457ba.mov

2021-01-12 03:54 UTC, ajuner commented
你这个demo是1.x版本的吧。。

2021-01-12 04:08 UTC, snowtreetree commented
https://codesandbox.io/s/nostalgic-water-juux5?file=/src/main.js
这个是2.0.0-rc.6版本的，你这边确认的时候是用的什么版本，😂。

2021-01-12 04:16 UTC, ajuner commented
https://codesandbox.io/s/pensive-nash-56xzn?file=/src/App.vue
神奇的问题，我这个是能停住的

2021-01-12 04:54 UTC, snowtreetree commented
![image](https://user-images.githubusercontent.com/30932683/104271209-44903200-54d5-11eb-8a49-92192f324301.png)
@ajuner 好像单独用是可以的，再在外面多加一层就不行了。

2021-01-13 12:51 UTC, tangjinzhou requested changes

2021-01-13 12:51 UTC, tangjinzhou commented on components/vc-slick/src/inner-slider.js
> +        onMouseenter: pauseOnDotsHover ? this.onDotsOver : noop,
I think we can delete onMouseenter event.

2021-01-13 12:52 UTC, tangjinzhou commented
删掉那一行应该没什么问题

2021-01-14 06:29 UTC, snowtreetree commented on components/vc-slick/src/inner-slider.js
> +        onMouseenter: pauseOnDotsHover ? this.onDotsOver : noop,
确实，这块onMouseover和onMouseenter处理情况有重复的地方。

2021-01-14 06:35 UTC, snowtreetree commented on components/vc-slick/src/inner-slider.js
> +        onMouseenter: pauseOnDotsHover ? this.onDotsOver : noop,
pauseOnHover 相关的 onMouseenter应该也可以删除，😂。

2021-01-14 07:42 UTC, merged