fix: breadcrumb separator display
vueComponent/ant-design-vue pull request #3522
Opened 2021-01-12 03:44 UTC by zkwolf

First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
> 2. Resolve what problem.
> 3. Related issue link.

### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

2021-01-12 07:01 UTC, John60676 commented on components/breadcrumb/BreadcrumbSeparator.tsx
> +        {(children.length > 0 && children) || '/'}
`children.length > 0 && children`  这段是不是写反了，而且 `&& children` 应该可以不写，`getSlot ` 貌似能确保返回的是数组

2021-01-12 09:51 UTC, zkwolf commented on components/breadcrumb/BreadcrumbSeparator.tsx
> +        {(children.length > 0 && children) || '/'}
getSlot就是确保返回数组啊，这里正确的逻辑是如果数组是空的返回'/'，否则返回children

2021-01-12 09:55 UTC, John60676 commented on components/breadcrumb/BreadcrumbSeparator.tsx
> +        {(children.length > 0 && children) || '/'}
哦，看错了 😂

2021-01-13 12:55 UTC, tangjinzhou requested changes

2021-01-13 12:55 UTC, tangjinzhou commented on components/breadcrumb/BreadcrumbSeparator.tsx
> +        {(children.length > 0 && children) || '/'}
```js
children.length > 0 ? children : '/'
```
改成这种吧

2021-01-14 02:12 UTC, merged