Update Table.jsx
vueComponent/ant-design-vue pull request #3626
Opened 2021-02-01 11:21 UTC by pengandpeng

### 这个变动的性质是

- [ ] 新特性提交
- [x] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 组件样式改进
- [ ] TypeScript 定义更新
- [ ] 重构
- [ ] 代码风格优化
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 需求背景

> 1. 使用table组件，需要同时满足表头固定（通过设置scroll属性）和可展开行（通过expandedRowRender slot）的需求。
> 2. 如果scroll和expandedRowRender同时设置报”`expandedRowRender` and `scroll` are not compatible. Please use one of them at one time.“，通过一些issue发现是为了避免固定列与可展开行的冲突，但是固定表头跟可展开行没有冲突，而且这种需求也很多，我自己也遇到了。
> 3. [expandedRowRender and scroll compatible #3326](https://github.com/vueComponent/ant-design-vue/issues/3326)。

### 请求合并前的自查清单

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2021-02-04 02:32 UTC, tangjinzhou requested changes

2021-02-04 02:32 UTC, tangjinzhou commented on components/table/Table.jsx
> +      !props.expandedRowRender || !('scroll' in props) || !props.scroll.x,
如果 props.scroll 不存在 那么props.scroll.x 会报错
这里还要做容错处理

2021-02-04 02:51 UTC, pengandpeng commented on components/table/Table.jsx
> +      !props.expandedRowRender || !('scroll' in props) || !props.scroll.x,
> 如果 props.scroll 不存在 那么props.scroll.x 会报错
> 这里还要做容错处理

如果props.scroll 不存在，!('scroll' in props)就是true，后面的不会执行了

2021-02-06 05:44 UTC, tangjinzhou commented on components/table/Table.jsx
> +      !props.expandedRowRender || !('scroll' in props) || !props.scroll.x,
yes  you are right

2021-02-06 05:45 UTC, tangjinzhou commented on components/table/Table.jsx
> +      !props.expandedRowRender || !('scroll' in props) || !props.scroll.x,
如果方便  可以再pr 一份到 next 分支  感谢

2021-02-06 05:46 UTC, merged