feat: update formItem rules then auto trigger validation
vueComponent/ant-design-vue pull request #4039
Opened 2021-05-07 18:13 UTC by Archer03

First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. 希望能动态修改 FormItem 的 rules 并立即触发一次校验
> 2. 目前 form 中的 validateOnRuleChange 是应用于整个表单的，表单字段较多时，不希望修改一个表单域就导致整个表单都触发校验
> 3. Related issue link.

### API Realization (Optional if not new feature)

> 1. 这个pr的解决方案：FormItem新增一个属性 validateOnRuleChange 控制是否使用此功能，新增一个计算属性 fieldRules 进行深度监听，以实现直接修改单个表单域的 rules 任意属性都能触发这个表单域的校验；其他替代方案：其实哪里改了rules 哪里就补 refs.xxxfield.validate('') 也是可行的，就是要多写几行代码，也要大量定义ref
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. 都是新增方法和属性；深度监听计算属性fieldRules有做注销监听处理；其他风险：在FormItem 的 validate 方法中，如果 rules 为空则直接返回true，但没有置空 validateState 和 validateMessage，这个pr补了上去 不知会不会有其他影响
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

2021-05-08 02:07 UTC, Archer03 commented
就想方便实现这种效果
![update-validation](https://user-images.githubusercontent.com/37865549/117522201-8729cd00-afe4-11eb-85a7-5b359e7844c0.gif)

2021-05-08 02:08 UTC, Archer03 commented
就想方便实现这种效果
![update-validation](https://user-images.githubusercontent.com/37865549/117522201-8729cd00-afe4-11eb-85a7-5b359e7844c0.gif)

2021-05-08 06:53 UTC, tangjinzhou requested changes

2021-05-08 06:53 UTC, tangjinzhou commented on antdv-demo/docs/form-model/demo/update-validation.md
> +        this.rules = JSON.parse(JSON.stringify(formRules));
用 lodash 的deepclone 吧

2021-05-08 06:53 UTC, tangjinzhou commented on antdv-demo/docs/form-model/index.zh-CN.md
> +| validateOnRuleChange | 是否在 rules 属性或 form 中为此表单域配置的 rules 改变后立即触发一次验证 | boolean | false |  |  |
添加版本支持信息  下个版本应该是1.7.5

2021-05-08 06:53 UTC, tangjinzhou commented on components/form-model/FormItem.jsx
> +        this.validateState = '';
这里不要改，这里应该不影响 validateOnRuleChange 需求吧   
这里rules本身是经过了过滤的，但直接清空校验状态，会把所有都清除

2021-05-08 11:45 UTC, Archer03 commented on antdv-demo/docs/form-model/demo/update-validation.md
> +        this.rules = JSON.parse(JSON.stringify(formRules));
感谢指点，已修改

2021-05-08 11:45 UTC, Archer03 commented on antdv-demo/docs/form-model/index.zh-CN.md
> +| validateOnRuleChange | 是否在 rules 属性或 form 中为此表单域配置的 rules 改变后立即触发一次验证 | boolean | false |  |  |
已添加

2021-05-08 11:45 UTC, Archer03 commented on components/form-model/FormItem.jsx
> +        this.validateState = '';
这里还是有影响的，如果rules真的被完全清空，这里不置空就会return true跳出validate，导致错误提示还留在页面。所以我加上了trigger === '' 的判断，看可不可以？这还是原有的一个bug，如果使用了form的validateOnRuleChange，在页面出现错误校验提示的情况下，再对form的rules属性重新赋值一个空对象，也会出现这个问题

2021-05-10 04:04 UTC, John60676 commented on components/form-model/FormItem.jsx
> +import { cloneDeep, isEqual } from 'lodash';
```js
import cloneDeep from 'lodash/cloneDeep';
import isEqual from 'lodash/isEqual';
```
改成这样吧

2021-05-11 01:54 UTC, Archer03 commented on components/form-model/FormItem.jsx
> +import { cloneDeep, isEqual } from 'lodash';
ok

2021-05-12 14:11 UTC, Archer03 commented
这个pr被我整得太乱了，之前不知道跑test一直报错，现在一堆commit记录。而且深度watch一个计算属性又极少看到这样的做法

2021-07-19 02:11 UTC, closed without merging