🎈 fix <a-statistic-countdown> slots error
vueComponent/ant-design-vue pull request #4996
Opened 2021-12-07 13:48 UTC by 24min

Fix <a-statistic-countdown> can't slot Bug

### This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> In the documentation on the official website, I found that the countdown component can slot title、suffix and prefix.But in my practice, this feature doesn't work correctly
>
> In this case, the problem of recurrence [[Vue Antd Template (forked) - CodeSandbox](https://codesandbox.io/s/vue-antd-template-forked-g41wx?file=/src/App.vue)].
>
> I tried to fix that, and that's why the PR came in.

### Self Check before Merge

- [x] Doc is updated/provided 
- [x] Demo is updated/provided

2021-12-07 14:48 UTC, tangjinzhou requested changes

2021-12-07 14:48 UTC, tangjinzhou commented on components/statistic/Countdown.tsx
> +          v-slots={{
v-slots={slots}  就可以了吧

2021-12-07 14:48 UTC, tangjinzhou commented on components/statistic/Countdown.tsx
> +          v-slots={{
v-slots={slots}  就可以了吧

2021-12-08 01:22 UTC, 24min commented on components/statistic/Countdown.tsx
> +          v-slots={{
谢谢，所以我这边是需要重新提交一个PR吗？

2021-12-08 02:39 UTC, merged