refactor(v3/vc-selector/input): use composition api
vueComponent/ant-design-vue pull request #5364
Opened 2022-03-19 11:20 UTC by buqiyuan

First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
> 2. Resolve what problem.
> 3. Related issue link.

### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

2022-03-19 13:40 UTC, buqiyuan commented
![image](https://user-images.githubusercontent.com/39730999/159122820-555c9cb9-7d1d-4547-a11e-b2bb772a068b.png)
为什么这里的a-textarea不能有自定义class

2022-03-20 02:16 UTC, tangjinzhou commented
bug

2022-03-20 02:30 UTC, tangjinzhou requested changes

2022-03-20 02:30 UTC, tangjinzhou commented on components/vc-select/Selector/Input.tsx
> +      return <InputNode {...inputProps}></InputNode>;
这么写应该默认合并了属性的，会支持触发原inputNode 的事件，这里又做了onOriginXXX ，应该会触发两次
class 也是这个原因，导致 class 挂载上了(反而成了正确的结果)，问题的根本原因是  `InputNode?.props?.className` 是错的，应该是 `InputNode?.props?.class`

2022-03-20 02:31 UTC, tangjinzhou commented on components/vc-select/Selector/Input.tsx
> +      return <InputNode {...inputProps}></InputNode>;
保留 cloneElement 的逻辑，className 改成 class  好了

2022-03-20 02:35 UTC, buqiyuan commented on components/vc-select/Selector/Input.tsx
> +      return <InputNode {...inputProps}></InputNode>;
ok

2022-03-20 02:40 UTC, buqiyuan commented on components/vc-select/Selector/Input.tsx
> +      return <InputNode {...inputProps}></InputNode>;
done

2022-03-20 02:50 UTC, merged

2022-03-20 02:56 UTC, buqiyuan commented
@tangjinzhou 对了，唐大佬，其实现在在业务中我对antdv的二次封装还遇到一些小问题，就是antdv导出的props中带有onXxx的事件函数的问题，会导致@ok这些事件会被vue合并成为一个数组，我觉得除了hook函数式使用的组件的props里的事件可以是onXxx，普通组件的props里不应当有onXxx，组件事件都应该是定义在emit中，这样的话 使用的时候volar也会有提示的，所以我现在遇到的小麻烦是如图所示，我需要把重复的事件omit掉：
![image](https://user-images.githubusercontent.com/39730999/159146049-79dd7e58-db4c-46f0-8342-145eedaca57d.png)
不知道我描述的清楚不

2022-03-20 02:59 UTC, buqiyuan commented
配上warn信息应该好理解：
![image](https://user-images.githubusercontent.com/39730999/159146118-c32a44fe-8f50-421b-a12c-8f487d0af021.png)