refactor(image): refactor & add new features
vueComponent/ant-design-vue pull request #5479
Opened 2022-04-10 17:34 UTC by buqiyuan

First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
> 2. Resolve what problem.
> 3. Related issue link.

### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

2022-04-11 06:10 UTC, tangjinzhou requested changes

2022-04-11 06:36 UTC, buqiyuan commented on components/image/__tests__/__snapshots__/demo.test.js.snap
> +    <div class="[object Object]-mask-info"><span role="img" aria-label="eye" class="anticon anticon-eye"><svg focusable="false" class="" data-icon="eye" width="1em" height="1em" fill="currentColor" a
是的 这里修复了
![image](https://user-images.githubusercontent.com/39730999/162678783-c7e6fc4c-de15-4404-9fa3-606eb41fa2e7.png)

2022-04-11 06:38 UTC, buqiyuan commented on components/image/demo/preview-group-visible.vue
> +    :preview="{ visible: false }"
`ant-design`那边是要禁用的
![image](https://user-images.githubusercontent.com/39730999/162678944-4d7f3606-a854-4abc-9321-aba2aa05b1fa.png)

2022-04-11 06:39 UTC, buqiyuan commented on components/image/index.zh-CN.md
> +  mask?: VNode;
好的 当时这里我也犹豫了下

2022-04-11 06:57 UTC, buqiyuan commented on components/vc-image/src/Image.tsx
> +              props.preview && !Object.is(previewVisible.value, false) && !isError.value
这样判断会好像会有点问题，`props.preview.visible`为`false`的`Image`应当被禁用预览

2022-04-11 06:58 UTC, buqiyuan commented on components/image/index.tsx
> +        mask: slots.previewMask ? (
那我直接改成这样可以吗？
![image](https://user-images.githubusercontent.com/39730999/162681957-e09ed834-f816-4a5b-a2b2-341c1f4d2356.png)

2022-04-11 07:14 UTC, buqiyuan commented on components/vc-image/src/Image.tsx
> +              props.preview && !Object.is(previewVisible.value, false) && !isError.value
`!Object.is(previewVisible.value, false)`应该还是要保留的，`props.preview.visible`为false的不应该调用`onPreview`，而是直接触发`click`

2022-04-12 01:07 UTC, tangjinzhou commented on components/image/index.tsx
> +        mask: slots.previewMask ? (
可以

2022-04-12 02:43 UTC, buqiyuan commented on components/vc-image/src/PreviewGroup.tsx
> +    const onPreviewAfterClose = () => {
done

2022-04-12 06:40 UTC, buqiyuan commented on components/vc-image/src/Image.tsx
> +      onChange: onPreviewVisibleChange.value,
已更正

2022-04-12 09:09 UTC, tangjinzhou requested changes

2022-04-12 09:09 UTC, tangjinzhou commented on components/vc-image/src/Preview.tsx
> +                {createVNode(IconType, { class: iconClassName })}
cloneVNode

2022-04-12 09:09 UTC, tangjinzhou commented on components/vc-image/src/PreviewGroup.tsx
> +    });
应该需要 immediate: true   吧
你可以测试下，受控显示 current:  1

2022-04-12 09:16 UTC, buqiyuan commented on components/vc-image/src/PreviewGroup.tsx
> +    });
是的 这里疏漏了

2022-04-12 09:18 UTC, buqiyuan commented on components/vc-image/src/Image.tsx
> +              <div class={`${prefixCls}-mask`}>{slots.previewMask()}</div>
😅啊对 漏了

2022-04-12 09:19 UTC, buqiyuan commented on components/vc-image/src/Image.tsx
> +              <div class={`${prefixCls}-mask`}>{slots.previewMask()}</div>
已补上

2022-04-13 00:53 UTC, tangjinzhou commented
![image](https://user-images.githubusercontent.com/6937879/163077834-551c4798-d063-4687-9b5a-eeae8bdc9187.png)
这两都没过

2022-04-13 01:15 UTC, buqiyuan commented
> ![image](https://user-images.githubusercontent.com/6937879/163077834-551c4798-d063-4687-9b5a-eeae8bdc9187.png) 这两都没过

😂同步了下[rc-dialog](https://github.com/react-component/dialog/blob/master/src/Dialog/index.tsx) `rootClassName`，代码里面没提示缺少这个属性 没注意

2022-04-13 02:47 UTC, Fox-ABC commented
这个版本什么时候会发布

2022-04-14 01:54 UTC, merged