fix(Image): can not cancel previewMask
vueComponent/ant-design-vue pull request #5531
Opened 2022-04-20 11:55 UTC by buqiyuan

First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
> 2. Resolve what problem.
> 3. Related issue link.

### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

2022-04-21 06:04 UTC, tangjinzhou commented
忘了说我的想法了：
我们不用支持吧，给他个方案就可以了  不是有 maskClassName 这个了吗，可以满足他了

2022-04-21 14:20 UTC, buqiyuan commented
> 忘了说我的想法了： 我们不用支持吧，给他个方案就可以了 不是有 maskClassName 这个了吗，可以满足他了

😂自定义`maskClassName`然后再设置`display: none;`吗？但这样感觉可能就没有将`previewMask`设置为`false`那么符合用户的直观，并且我也体验了一下`vc-image`，
![image](https://user-images.githubusercontent.com/39730999/164475349-82182650-996b-47e5-8f7c-91520c5a3c12.png)
在上面这个逻辑中，previewMask的值为`falsy`的时候都不会渲染`mask`，由于我们的`previewMask`是`slot`所以始终为`truthy`。所以我觉得这样也符合`vc-image`原本的一个逻辑，`previewMask`也相对于`maskClassName`更语义化一些，这次提交 我也移除了很多 多余的代码

2022-04-22 02:18 UTC, tangjinzhou requested changes

2022-04-22 02:18 UTC, tangjinzhou commented on components/image/index.en-US.md
> +| previewMask | custom mask | boolean \| VNode \| VNode[] \| slot | true | 3.2.0 |
`boolean  \| function \| slot`   默认值 undefined
只要 previewMask 是 undefined 就取 slot

2022-04-22 02:18 UTC, tangjinzhou commented on components/image/index.tsx
> +              props.previewMask === false
`props.previewMask === false ? null : (props.previewMask ?? slots.previewMask)`

2022-04-22 05:23 UTC, buqiyuan commented on components/image/index.en-US.md
> +| previewMask | custom mask | boolean \| VNode \| VNode[] \| slot | true | 3.2.0 |
done

2022-04-22 08:22 UTC, merged