fix: use fromPairs replace Object.fromEntries
vueComponent/ant-design-vue pull request #5605
Opened 2022-05-16 07:35 UTC by wen81643956

### This is a bugfix

### What's the background?

> 1. fix: [#5168](https://github.com/vueComponent/ant-design-vue/issues/5168)

### API Realization (Optional if not new feature)

> 1. use lodash fromPairs replace Object.fromEntries

### What's the effect? (Optional if not new feature)

> 1. we can run it in a development environment with earlier versions of browsers

### Changelog description (Optional if not new feature)

> 1. fix: use fromPairs replace Object.fromEntries

2022-05-16 07:40 UTC, wen81643956 commented
this pr is refer to [element-plus pr](https://github.com/element-plus/element-plus/pull/3422)

2022-05-17 14:20 UTC, tangjinzhou requested changes

2022-05-17 14:20 UTC, tangjinzhou commented on components/_util/reactivePick.ts
> +import fromPairs from 'lodash/fromPairs';
use `lodash-es/fromPairs`

2022-05-19 02:40 UTC, wen81643956 commented on components/_util/reactivePick.ts
> +import fromPairs from 'lodash/fromPairs';
replaced

2022-05-20 08:19 UTC, merged