refactor(empty): less to cssinjs
vueComponent/ant-design-vue pull request #6230
Opened 2023-02-05 16:42 UTC by buqiyuan

First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [x] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
> 2. Resolve what problem.
> 3. Related issue link.

### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

2023-02-06 14:59 UTC, tangjinzhou requested changes

2023-02-06 14:59 UTC, tangjinzhou commented on components/empty/simple.tsx
> +    const { colorFill, colorFillTertiary, colorFillQuaternary, colorBgContainer } = token.value;
直接结构出来就失去响应式了

2023-02-06 14:59 UTC, tangjinzhou commented on components/empty/index.tsx
> +    const {
直接结构出来就失去响应式了
原来是函数式组件，不存在这个问题，你现在改成普通组件，就会问题了，放在return 里面

2023-02-06 14:59 UTC, tangjinzhou commented on components/empty/index.tsx
> +const Empty = defineComponent({
定义 props
添加 inheritAttrs: false,

2023-02-06 14:59 UTC, tangjinzhou commented on components/empty/index.tsx
> +    const prefixCls = prefixClsRef.value;
失去响应式了

2023-02-06 14:59 UTC, tangjinzhou commented on components/empty/index.tsx
> +    const prefixCls = prefixClsRef.value;
原来是函数式组件，不存在这个问题，你现在改成普通组件，就会问题了，放在return 里面

2023-02-06 16:26 UTC, buqiyuan commented on components/empty/simple.tsx
> +    const { colorFill, colorFillTertiary, colorFillQuaternary, colorBgContainer } = token.value;
我的，粗心了

2023-02-07 01:57 UTC, tangjinzhou approved these changes

2023-02-07 01:57 UTC, merged