Feat v4 floatbutton
vueComponent/ant-design-vue pull request #6294
Opened 2023-02-19 12:01 UTC by shifeng1993

First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
> 2. Resolve what problem.
> 3. Related issue link.

### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

2023-02-19 12:03 UTC, shifeng1993 commented on site/index.html
> +    ></div> -->
广告把 floatbutton盖住了，暂时注释掉

2023-02-19 12:04 UTC, shifeng1993 commented
以前的 backtop 文件夹要删掉吗？

2023-02-19 16:13 UTC, tangjinzhou commented
> 以前的 backtop 文件夹要删掉吗？

先不删，review 的时候我再看看

2023-02-28 08:10 UTC, tangjinzhou requested changes

2023-02-28 08:10 UTC, tangjinzhou commented on components/float-button/FloatButton.tsx
> +        attrs.class,
attrs.class, 不是响应式的

2023-02-28 08:10 UTC, tangjinzhou commented on components/float-button/FloatButton.tsx
> +  FloatButton.displayName = 'FloatButton';
同上一个组件

2023-02-28 08:10 UTC, tangjinzhou commented on components/float-button/FloatButtonContent.tsx
> +  props: initDefaultProps(floatButtonContentProps(), {}),
没有默认值就不用加了

2023-02-28 15:01 UTC, shifeng1993 commented on site/src/router/index.js
> +      {
这里放的是iframe套的例子，我试了一下重启服务 路由构建脚本 没有添加上

2023-02-28 15:08 UTC, shifeng1993 commented
这次提交的 文件 components/_util/transition.tsx
会影响到floatbutton  groupmenu的动画样式 

https://github.com/vueComponent/ant-design-vue/commit/f39d4894e4b5a7646574658a6ce97a1d560c96b9

components/float-button-cn#components-float-button-demo-group-menu

2023-03-01 09:25 UTC, tangjinzhou commented
> 这次提交的 文件 components/_util/transition.tsx 会影响到floatbutton groupmenu的动画样式
> 
> [f39d489](https://github.com/vueComponent/ant-design-vue/commit/f39d4894e4b5a7646574658a6ce97a1d560c96b9)
> 
> components/float-button-cn#components-float-button-demo-group-menu

这个我来看看

有兴趣的话留个微信号，拉你进我们微信群

2023-03-01 09:27 UTC, tangjinzhou requested changes

2023-03-01 09:27 UTC, tangjinzhou commented on components/float-button/FloatButtonGroup.tsx
> +      shape: props.shape,
改成这样就丢失响应式了吧

2023-03-01 11:24 UTC, shifeng1993 commented
> > 这次提交的文件components/_util/transition.tsx会影响到floatbutton groupmenu的动画样式
> > [f39d489](https://github.com/vueComponent/ant-design-vue/commit/f39d4894e4b5a7646574658a6ce97a1d560c96b9)
> > 组件/float-button-cn#components-float-button-demo-group-menu
> 
> 这个我来看看
> 
> 有兴趣的话留个微信，拉你进入我们微信群@shifeng1993

sf542674656

2023-03-01 15:50 UTC, shifeng1993 commented
createContext  这个函数用 reactive包一层  内部的ref，在用ref的时候会去掉.value 很奇怪。

2023-03-02 02:47 UTC, tangjinzhou commented
> 我看看

2023-03-02 02:59 UTC, merged