feat: add qrcode
vueComponent/ant-design-vue pull request #6315
Opened 2023-02-27 12:23 UTC by selicens

First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
> 2. Resolve what problem.
> 3. Related issue link.

### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

2023-02-27 12:51 UTC, selicens commented
qrcode组件相关：因为antdesign是使用了qrcode.react的库，所以参照jeecgboot-vue3的二维码组件使用了qrcode这个库来实现，npm地址：[https://www.npmjs.com/package/qrcode](https://www.npmjs.com/package/qrcode)，github仓库：[github.com/soldair/node-qrcode](https://github.com/soldair/node-qrcode)，二维码中心icon使用了canvas 2D API的drawImage()方法在canvas中绘制

2023-02-28 03:29 UTC, tangjinzhou requested changes

2023-02-28 03:29 UTC, tangjinzhou commented on components/qrcode/index.tsx
> +  name: 'AQrCode',
AQrcode  这样吧，使用的时候方便 a-qrcode

2023-02-28 03:29 UTC, tangjinzhou commented on components/qrcode/index.en-US.md
> +| onRefresh | callback | `() => void` | - |
事件单独列出

2023-02-28 03:29 UTC, tangjinzhou commented on components/qrcode/interface.ts
> +export interface QRCodeProps extends QRProps {
直接用 组件的 QRCodeProps 就好了，不用额外在写一份了

2023-02-28 03:29 UTC, tangjinzhou commented on components/qrcode/index.tsx
> +  methods: {
不要混用 composition api  和 options api

2023-02-28 03:29 UTC, tangjinzhou commented on components/qrcode/index.tsx
> +    const qrcodeCanvasProps: QRCodeCanvasProps = {
响应式丢失了

2023-02-28 03:29 UTC, tangjinzhou commented on components/qrcode/index.tsx
> +    if (process.env.NODE_ENV !== 'production') {
我们是新组件，没有历史包袱，不推荐的属性就不用加进去了

2023-02-28 03:29 UTC, tangjinzhou commented on components/qrcode/index.tsx
> +        <LocaleReceiver
参考其他组件用  useLocaleReceiver

2023-02-28 03:29 UTC, tangjinzhou commented on components/qrcode/index.tsx
> +                        <p class={classNames(`${pre}-expired`)}>二维码已过期</p>
？  怎么还出现了 中文

2023-02-28 03:29 UTC, tangjinzhou commented on components/qrcode/index.tsx
> +                        <p class={classNames(`${pre}-expired`)}>二维码已过期</p>
国际化内容应该在  components/locale 下面添加

2023-02-28 05:00 UTC, selicens commented on components/qrcode/index.tsx
> +  name: 'AQrCode',
1

2023-02-28 08:12 UTC, tangjinzhou requested changes

2023-02-28 08:12 UTC, tangjinzhou commented on components/qrcode/index.tsx
> +    if (!props.value) {
属性上面声明 value 为必填就好了

2023-03-01 09:35 UTC, tangjinzhou requested changes

2023-03-01 09:35 UTC, tangjinzhou commented on components/qrcode/index.tsx
>      const pre = prefixCls.value;
在 setup 里面直接拿到的 .value  值，赋值给一个新的变量，这个新变量都是没有响应式的

2023-03-01 09:35 UTC, tangjinzhou commented on components/qrcode/index.tsx
> +    const { value, size, status, bordered } = toRefs(props);
这几个值没必要转一次吧，都没做什么操作啊 
直接放到 return 里面解构就好了

2023-03-01 10:36 UTC, selicens commented on components/qrcode/index.tsx
> +    const { value, size, status, bordered } = toRefs(props);
1

2023-03-02 02:46 UTC, merged