Feat(DatePicker ): increase presets prop
vueComponent/ant-design-vue pull request #6387
Opened 2023-03-25 08:55 UTC by CCherry07

First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to master branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](https://github.com/vueComponent/ant-design-vue/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]

### This is a ...

- [x] New feature
- [ ] Bug fix
- [x] Site / document update
- [ ] Component style update
- [x] TypeScript definition update
- [x] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
增加 presets 属性 预设时间范围快捷选择
> 2. Resolve what problem.
增加 presets 属性 预设时间范围快捷选择
> 3. Related issue link.
#6354 
### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
增加usePresets hook 转化 presets 属性值
> 2. List final API realization and usage sample.
```vue
<template>
  <a-space direction="vertical" :size="12">
    <a-date-picker :presets="presets" @change="onChange" />
    <a-range-picker :presets="rangePresets" @change="onRangeChange" />
    <a-range-picker
      style="width: 400px"
      show-time
      format="YYYY/MM/DD HH:mm:ss"
      :presets="rangePresets"
      @change="onRangeChange"
    />
  </a-space>
</template>

<script setup lang="ts">
  const presets = [
    { label: 'Yesterday', value: dayjs().add(-1, 'd') },
    { label: 'Last Week', value: dayjs().add(-7, 'd') },
    { label: 'Last Month', value: dayjs().add(-1, 'month') },
  ];
<script lang="ts">
```
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
增加新prop
> 2. What will say in changelog?
无
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
The preset ranges for quick selection
> 2. Chinese description (optional)
预设时间范围快捷选择
### Self Check before Merge

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

2023-03-25 09:40 UTC, Wxh16144 commented on components/date-picker/index.en-US.md
> +| presets | The preset ranges for quick selection | { label: slot, value: [dayjs](https://day.js.org/) }[] | - |  |
可以顺手补一个 version 说明从那个版本开始支持的

2023-03-25 09:40 UTC, Wxh16144 commented on components/date-picker/index.zh-CN.md
> +| presets | 预设时间范围快捷选择 | { label: slot, value: [dayjs](https://day.js.org/) }[] | - |  |
同上

2023-03-25 09:40 UTC, Wxh16144 commented on components/vc-picker/Picker.tsx
> +          prefixCls = 'vc-picker',
不做更改

2023-03-27 00:33 UTC, tangjinzhou requested changes

2023-03-27 00:33 UTC, tangjinzhou commented on components/vc-picker/Picker.tsx
> +      const presetList = usePresets(props.presets);
这里丢失响应式了 
usePresets 的参数应该是 ref 或 computedRef

2023-03-27 00:33 UTC, tangjinzhou commented on components/vc-picker/Picker.tsx
> +      const presetList = usePresets(props.presets);
同样包括返回的数据也应该是响应式的

2023-03-27 00:33 UTC, tangjinzhou commented on components/vc-picker/hooks/usePresets.ts
> +export default function usePresets<T>(
输入、返回 要是响应式的

2023-03-27 11:32 UTC, zkwolf commented on components/vc-picker/hooks/usePresets.ts
> +export default function usePresets<T>(
用到的地方似乎都只输入了第一个参数？感觉这方法用处不大啊，不如直接删了

2023-04-01 10:38 UTC, CCherry07 reviewed
review is ok

2023-04-05 02:48 UTC, tangjinzhou commented on components/vc-picker/hooks/usePresets.ts
> +  if (presets.value) {
这样还是有问题的，同样丢失了响应式

2023-04-05 02:50 UTC, tangjinzhou commented on components/vc-picker/hooks/usePresets.ts
> +  if (presets.value) {
我先 merge 修改，你在看下改动

2023-04-05 02:51 UTC, CCherry07 commented on components/vc-picker/hooks/usePresets.ts
> +  if (presets.value) {
好的

2023-04-05 02:55 UTC, tangjinzhou approved these changes

2023-04-05 02:56 UTC, merged

2023-04-05 02:56 UTC, CCherry07 commented on components/vc-picker/hooks/usePresets.ts
> +  if (presets.value) {
```ts
      const presets = computed(() => props.presets);
      const ranges = computed(() => props.ranges);
      const presetList = usePresets(presets, ranges);
```
并没有吧，usePresets 返回的是一个计算属性，如果presets.value 存在 就是直接 返回的 presets 计算属性