refactor(progress): enhance size prop and add variants
vueComponent/ant-design-vue pull request #6409
Opened 2023-03-30 11:35 UTC by CCherry07

首先，感谢你的贡献！ 😄

新特性请提交至 feature 分支，其余可提交至 master 分支。在一个维护者审核通过后合并。请确保填写以下 pull request 的信息，谢谢！~

[[English Template / 英文模板](?expand=1)]

### 这个变动的性质是

- [x] 新特性提交
- [x] 日常 bug 修复
- [x] 站点、文档改进
- [x] 组件样式改进
- [x] TypeScript 定义更新
- [x] 重构
- [ ] 代码风格优化
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 需求背景

> 1. 描述相关需求的来源。
增强 size 属性
deprecated width 属性
> 2. 要解决的问题。
增强 size 属性
deprecated width 属性
> 3. 相关的 issue 讨论链接。
#6355
### 实现方案和 API（非新功能可选）

> 1. 基本的解决思路和其他可选方案。
增加 getsize 函数 处理 以往兼容性问题
重构 size<= 20时触发变体
> 2. 列出最终的 API 实现和用法。
```vue
<template>
  <div>
    <a-progress
      type="circle"
      trail-color="#e6f4ff"
      :percent="60"
      :stroke-width="20"
      :size="12"
      :format="number => `进行中，已完成${number}%`"
    />
    <span :style="{ marginLeft: 8 }">代码发布</span>
  </div>
</template>
```
> 3. 涉及 UI/交互变动需要有截图或 GIF。
![Uploading image.png…]()

### 对用户的影响和可能的风险（非新功能可选）

> 1. 这个改动对用户端是否有影响？影响的方面有哪些？
Progress 组件
```ts
if (process.env.NODE_ENV !== 'production') {
  devWarning(
    'successPercent' in props,
    'Progress',
    '`successPercent` is deprecated. Please use `success.percent` instead.',
  );
  devWarning('width' in props, 'Progress', '`width` is deprecated. Please use `size` instead.');
}
```
progress 下 line 组件
```ts
if (process.env.NODE_ENV !== 'production') {
  devWarning(
    'strokeWidth' in props,
    'Progress',
    '`strokeWidth` is deprecated. Please use `size` instead.',
  );
}
```
> 2. 是否有可能隐含的 break change 和其他风险？
无
### Changelog 描述（非新功能可选）

> 1. 英文描述
enhance size prop and add variants
> 2. 中文描述（可选）
增强 size prop和添加变体
### 请求合并前的自查清单

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

### 后续计划（非新功能可选）

> 如果这个提交后面还有相关的其他提交和跟进信息，可以写在这里。

2023-03-31 16:16 UTC, CCherry07 reviewed
@tangjinzhou  review is ok

2023-04-06 06:56 UTC, tangjinzhou requested changes

2023-04-06 06:56 UTC, tangjinzhou commented on components/vc-progress/src/Circle.tsx
> +        class: className,
class 不需要单独声明的，会自动挂到根节点的（前提：没有使用 inheritAttrs: false，没有将class 声明到props 里面）

2023-04-06 06:56 UTC, tangjinzhou commented on components/vc-progress/src/types.ts
> +  class: String,
同上

2023-04-06 07:11 UTC, tangjinzhou approved these changes

2023-04-06 07:11 UTC, merged