feat: add static-style-extract
vueComponent/ant-design-vue pull request #6713
Opened 2023-07-05 09:32 UTC by aibayanyu20

close #6659

2023-07-06 01:47 UTC, tangjinzhou requested changes

2023-07-06 01:47 UTC, tangjinzhou commented on components/_util/static-style-extract/index.tsx
> +const blackList: string[] = [
怎么那么多

2023-07-06 01:52 UTC, aibayanyu20 commented on components/_util/static-style-extract/index.tsx
> +const blackList: string[] = [
哪种嵌套在父组件中的子组件不用执行吧，单独执行的话依赖注入会报错，[ant-design](https://github.com/ant-design/ant-design/blob/master/components/index.ts)里面他哪些子组件都是通过Menu.Item这种方式调用的咱们这边是直接导出的

2023-07-06 14:12 UTC, aibayanyu20 commented on components/_util/static-style-extract/index.tsx
> +const blackList: string[] = [
删掉了一些可以删除的组件其他的大部分都是嵌套的组件

2023-07-06 15:43 UTC, selvinzr commented
等了很久了

2023-08-02 00:55 UTC, FreeDrifter commented
还没好 ?

2023-08-06 04:28 UTC, merged