fix(Tabs): dropdown show
vueComponent/ant-design-vue pull request #6757
Opened 2023-07-18 15:09 UTC by CCherry07

#6727

2023-07-29 04:15 UTC, tangjinzhou requested changes

2023-07-29 04:15 UTC, tangjinzhou commented on components/tabs/src/TabNavList/OperationNode.tsx
> +      if (!tabs.length) return null;
moreNode 等于 null 就好了吧

2023-07-31 00:51 UTC, tangjinzhou commented
没改啊 ？

2023-07-31 02:55 UTC, CCherry07 commented
> 

必须把这里所有的dom都要卸载掉，如果只有morenode卸载，下面的AddButton也会显示的
```tsx
        <div
          class={classNames(`${prefixCls}-nav-operations`, attrs.class)}
          style={attrs.style as CSSProperties}
        >
          {moreNode}
          <AddButton prefixCls={prefixCls} locale={locale} editable={editable} />
        </div>
```

2023-08-03 02:37 UTC, wangmin0314 commented
改好了请艾特我一下，谢谢

2023-08-06 03:50 UTC, merged

2023-08-23 01:22 UTC, huangfuwenhao commented
Tabs 这个 bug 终于修复了，感谢大佬们的辛勤维护，点赞👍