fix(modal): add onUpdate:open prop
vueComponent/ant-design-vue pull request #6876
Opened 2023-08-22 06:25 UTC by kovsu

fix: #6875

2023-08-22 06:54 UTC, catpigdog commented
> 修复：#6875

啊？哥们这么神速吗

2023-08-30 06:47 UTC, tangjinzhou requested changes

2023-08-30 06:47 UTC, tangjinzhou commented on components/modal/Modal.tsx
> +  'onUpdate:open': Function as PropType<(open: boolean) => void>,
visible 也得留着兼容，下个大版本才去掉

2023-08-30 06:47 UTC, tangjinzhou commented on components/modal/Modal.tsx
> +      emit('update:open', true);
这里加这个干嘛的

2023-08-30 06:53 UTC, kovsu commented on components/modal/Modal.tsx
> +      emit('update:open', true);
点击 ok 不应该也要触发一下 open 更新吗？😥

2023-08-30 07:09 UTC, tangjinzhou commented on components/modal/Modal.tsx
> +      emit('update:open', true);
只有打开的时候，你才能看到 OK，此时就是 open 状态，触发他的意义是什么呢

2023-08-30 07:18 UTC, kovsu commented on components/modal/Modal.tsx
> +      emit('update:open', true);
我想的应该是，一时间没转过来
```ts
emit('update:open', false);
```

2023-08-30 07:31 UTC, tangjinzhou commented on components/modal/Modal.tsx
> +      emit('update:open', true);
那也不应该触发，ok 会涉及一些异步操作，如果加了，要做很多的工作去适配异步的问题

2023-08-30 08:18 UTC, merged

2024-01-02 09:55 UTC, woohs commented
升级这个版本后，导致 vite 构建报错，请问有什么办法能解决？

<img width="515" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/31387031/db68ff6c-b0b9-4c49-aa9b-694ab4b3cd2b">