fix(transfer): checkbox click evt run repeatedly
vueComponent/ant-design-vue pull request #6903
Opened 2023-08-28 10:03 UTC by kovsu

fix: #6010

![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/b1ea3e38-53b4-42e4-91f1-72c12598b95a)

2023-08-30 08:13 UTC, tangjinzhou requested changes

2023-08-30 08:13 UTC, tangjinzhou commented on components/transfer/style/index.less
> +      .ant-checkbox {
这里直接写死了 ant 前缀

2023-08-30 08:16 UTC, kovsu commented on components/transfer/style/index.less
> +      .ant-checkbox {
因为好像那里用的是组件，然后有个 top 属性，我只能这样重置了。

2023-08-30 08:17 UTC, tangjinzhou commented on components/transfer/style/index.less
> +      .ant-checkbox {
啊  这不对啊，用的组件也是支持自定义的啊

2023-08-30 08:21 UTC, kovsu commented on components/transfer/style/index.less
> +      .ant-checkbox {
4.x 那个应该是没问题的，我给 antd 也提了 pr，合了

2023-08-30 08:36 UTC, kovsu commented on components/transfer/style/index.less
> +      .ant-checkbox {
```ts
<li
  ...
>
  <Checkbox
    class={`${prefixCls}-checkbox`}
    checked={checked}
    disabled={disabled || item.disabled}
  />
  {labelNode}
</li>
```
他这里是这样，然后是因为 checkbox 组件里面的一个 span 的样式有 top: 0.2em 属性，就会导致下面这样
![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/303a95b4-216b-4678-99de-c28eef466c6e)

```css
& > span {
  top: 0;
}
```
不写死 .ant 前缀的话，像这样吗？感觉没啥区别

2023-08-30 23:46 UTC, tangjinzhou commented on components/transfer/style/index.less
> +      .ant-checkbox {
ant 这个用户可以自定义的，用户如果改成abc，你给写死了不就不生效了

2023-08-31 00:48 UTC, kovsu commented on components/transfer/style/index.less
> +      .ant-checkbox {
```css
& > span {
  top: 0;
}
```
那就这样？

2023-09-09 01:22 UTC, merged