chore: update test
vueComponent/ant-design-vue pull request #6916
Opened 2023-08-31 07:35 UTC by kovsu

2023-09-01 01:57 UTC, tangjinzhou requested changes

2023-09-01 01:57 UTC, tangjinzhou commented on package.json
> -    "@vue/eslint-config-prettier": "^8.0.0",
为啥不升 prettier

2023-09-01 01:58 UTC, kovsu commented on package.json
> -    "@vue/eslint-config-prettier": "^8.0.0",
升了好像有些 api 用不了。
https://stackoverflow.com/questions/76624993/prettier-3-0-0-typeerror-prettier-resolveconfig-sync-is-not-a-function
这个

2023-09-01 02:37 UTC, kovsu commented
我来试一下

2023-09-01 03:04 UTC, kovsu commented
[pretty-quick](https://github.com/azz/pretty-quick/issues/164) 这个依赖在 prettie 3.x 下有问题，所以我觉得还是不要升版本了吧

2023-09-01 03:06 UTC, kovsu commented
他们提供的解决方案是用 lint-staged 替代

2023-09-15 06:24 UTC, kovsu commented
@tangjinzhou 这个要不要开个分支，用 lint-staged 替换 pretty-quick

2023-12-18 06:08 UTC, kovsu commented
![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/68912844-376c-4aa4-ab30-2cd1a798ae2e)

![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/38e5e306-bbee-4faa-b159-9f114a0201c4)

目前只有一个测试用例不过，而且感觉上像是一个 bug

2023-12-18 07:28 UTC, kovsu commented
![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/04425617-daa1-4ab8-a34d-880ccc115a1c)

2023-12-18 08:04 UTC, kovsu commented
lint: 
![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/1c145469-6081-4ac3-bbc7-dac6d89236b4)

2023-12-18 08:27 UTC, closed without merging