fix(select): list scrollbar height and timing (#6987)
vueComponent/ant-design-vue pull request #7001
Opened 2023-10-02 19:28 UTC by selicens

First of all, thank you for your contribution! 😄

New feature please send pull request to feature branch, and rest to main branch. Pull request will be merged after one of collaborators approve. Please makes sure that these form are filled before submitting your pull request, thank you!

[[中文版模板 / Chinese template](./pr_cn.md)]

### This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Branch merge
- [ ] Other (about what?)

### What's the background?

> 1. Describe the source of requirement.
> 2. Resolve what problem.
> 3. Related issue link.

### API Realization (Optional if not new feature)

> 1. Basic thought of solution and other optional proposal.
> 2. List final API realization and usage sample.
> 3. GIF or snapshot should be provided if includes UI/interactive modification.

### What's the effect? (Optional if not new feature)

> 1. Does this PR affect user? Which part will be affected?
> 2. What will say in changelog?
> 3. Does this PR contains potential break change or other risk?

### Changelog description (Optional if not new feature)

> 1. English description
> 2. Chinese description (optional)

### Self Check before Merge

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### Additional Plan? (Optional if not new feature)

> If this PR related with other PR or following info. You can type here.

2023-10-08 09:15 UTC, wsxe9988 commented
@tangjinzhou 太久没有review。  不少人提了pr,及时review 发版么

2023-10-16 03:06 UTC, tangjinzhou requested changes

2023-10-16 03:06 UTC, tangjinzhou commented on components/vc-virtual-list/List.tsx
> +        onMousemove={debounce(mousemove, 500)}
这个不需要吧，像mac滚动后显示滚动条，也不会因为鼠标移动影响滚动条的显示隐藏

2023-10-16 03:23 UTC, selicens commented on components/vc-virtual-list/List.tsx
> +        onMousemove={debounce(mousemove, 500)}
antd展开2s后隐藏滚动条，滚动或者鼠标重新移入会再次显示，antdv这边鼠标重新移入是不会出现滚动条，[#6987](https://github.com/vueComponent/ant-design-vue/issues/6987)

2023-10-16 06:33 UTC, tangjinzhou commented
我做了改动

2023-10-16 06:33 UTC, merged