fix(FloatButton): BackTop attribute invalid
vueComponent/ant-design-vue pull request #7009
Opened 2023-10-08 12:21 UTC by selicens

[#7008 ](https://github.com/vueComponent/ant-design-vue/issues/7008)
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/69bdcc21-c711-4057-a078-969927f55ee1)
将inheritAttrs删除是因为组件内有消费attrs，type从props中取则是被声明过的props无法从attribute中获取

2023-10-09 01:45 UTC, selicens commented
搞混了一个点，inheritAttrs为false时，通过attrs是能够手动消费透传，而且wrapSSR下inheritAttrs需为false

2023-10-09 06:32 UTC, selicens commented
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/16e15423-8b4e-4f25-963f-e7c1d4f7b599)
齐活

2023-10-16 02:45 UTC, tangjinzhou requested changes

2023-10-16 02:45 UTC, tangjinzhou commented on components/float-button/BackTop.tsx
> +              icon: () => slots.default?.() || slots.icon?.() || <VerticalAlignTopOutlined />,
我发现 default 是没有用到的吧,   就去掉吧，留着以后万一要加点什么

2023-10-16 02:54 UTC, selicens commented on components/float-button/BackTop.tsx
> +              icon: () => slots.default?.() || slots.icon?.() || <VerticalAlignTopOutlined />,
1

2023-10-16 06:21 UTC, merged