fix: support vue3.4.x to ant-design-vue 3.x
vueComponent/ant-design-vue pull request #7252
Opened 2024-01-06 13:16 UTC by selicens

synch 4.0

2024-01-09 05:11 UTC, menghany commented
@tangjinzhou 是否考虑发布兼容版本？目前3.x版本存量用户还有很多

2024-01-12 02:28 UTC, tangjinzhou requested changes

2024-01-12 02:28 UTC, tangjinzhou commented on components/affix/index.tsx
> +          <div {...restProps} ref={placeholderNode} data-measure-status={status}>
这个是不是多了一个 div，再核对下

2024-01-12 02:34 UTC, selicens commented on components/affix/index.tsx
> +          <div {...restProps} ref={placeholderNode} data-measure-status={status}>
1

2024-01-29 05:35 UTC, wsxe9988 commented
@tangjinzhou 是否考虑发布兼容版本？目前3.x版本存量用户还有很多

2024-02-02 05:47 UTC, wsxe9988 commented
@tangjinzhou 唐老师，3.x版本能不能把这个pr合并进去，发个bugfix版本，解决下vue升级到3.4以后出现的问题，毕竟还有不少人在用3.x

2024-02-19 02:58 UTC, TLovers commented
啥时候能发一版啊，大佬们

2024-02-23 07:16 UTC, wsxe9988 commented
@tangjinzhou @selicens 唐老师，3.x版本能不能把这个pr合并进去，发个bugfix版本，解决下vue升级到3.4以后出现的问题，毕竟还有不少人在用3.x

2024-02-26 02:59 UTC, johnnyhwa commented
啥时候能发一版啊，大佬们

2024-02-26 04:09 UTC, selicens commented
我再跟进一些

2024-03-04 02:33 UTC, TLovers commented
> 我再跟进一些

大佬，有消息吗

2024-03-14 12:52 UTC, jvalrog commented
My company is also being impacted by this. We have multiple widget libraries using ant-design-vue 3.x and new projects with vue 3.4 are broken.

2024-03-22 06:48 UTC, xingxing0804 commented
ant-design-vue 4.x 和vue3.4.x Modal.confirm无法关闭

2024-04-07 02:26 UTC, Yuliang-Lee commented
这个没进展了吗

2024-04-08 01:30 UTC, TLovers commented
> 这个没进展了吗

自己本地patch个补丁，自己玩自己的  😄

2024-04-08 06:55 UTC, Yuliang-Lee commented
> > 这个没进展了吗
> 
> 自己本地patch个补丁，自己玩自己的 😄

这个在 ci 机器上打包用的还是本地 patch 这个包吗

2024-04-08 09:32 UTC, TLovers commented
> > > 这个没进展了吗
> > 
> > 
> > 自己本地patch个补丁，自己玩自己的 😄
> 
> 这个在 ci 机器上打包用的还是本地 patch 这个包吗

shide

2024-04-10 12:37 UTC, kortin99 commented
还是没进展吗，

2024-04-11 01:50 UTC, TLovers commented
> 还是没进展吗，

催催唐老师，我看3.x版本修复了好几个问题，都没有发布，估计是JSX全局命名在3.4没有了，导致一直失败

2024-07-18 06:37 UTC, Yuliang-Lee commented
> > > > 这个没进展了吗
> > > 
> > > 
> > > 自己本地patch个补丁，自己玩自己的 😄
> > 
> > 
> > 这个在 ci 机器上打包用的还是本地 patch 这个包吗
> 
> shide

哥，这个要怎么做，能提供个 gist 参考下吗

2024-09-12 04:21 UTC, hengistchan commented
@selicens 还有进展吗？

2024-09-13 09:46 UTC, selicens commented
> @selicens 有进展吗？ @tangjinzhou 唐老师再看看？

没有，可能v3维护周期已经到了，建以采用patch的形式处理

2024-09-13 11:34 UTC, spacekong commented
这个没进展了么？真的是踩大坑了....

2024-09-14 14:44 UTC, hengistchan commented
> > @selicens 有进展吗？ @tangjinzhou 唐老师再看看？
> 
> 没有，可能v3维护周期已经到了，建以采用patch的形式处理

v4 一堆 mr 也没合并

2024-10-12 09:56 UTC, ZedCoding commented
antdv3.2.20啥时候能发一版啊

2024-10-13 05:28 UTC, selicens commented
> antdv3.2.20啥时候能发一版啊

应该不得发了，建议自行patch

2024-10-14 01:52 UTC, ZedCoding commented
> > antdv3.2.20啥时候能发一版啊
> 
> 应该不得发了，建议自行patch

可惜了 自己patch会不会很容易被npm i覆盖  (看来antdv3.2.20用不了vue新版本了)

2024-10-15 07:45 UTC, TLovers commented
> antdv3.2.20啥时候能发一版啊

让唐老师亮出收款码吧，一人一点捐助下！我看下不知道理解的对不对，好像就是vue 的ts的命名空间改了导致一直失败

2024-10-15 07:46 UTC, TLovers commented
> > > antdv3.2.20啥时候能发一版啊
> > 
> > 
> > 应该不得发了，建议自行patch
> 
> 可惜了 自己patch会不会很容易被npm i覆盖 (看来antdv3.2.20用不了vue新版本了)

不会，你都自己patch怎么会被覆盖呢？

2024-10-15 09:11 UTC, ZedCoding commented
> > antdv3.2.20啥时候能发一版啊
> 
> 让唐老师亮出收款码吧，一人一点捐助下！我看下不知道理解的对不对，好像就是vue 的ts的命名空间改了导致一直失败

哈哈哈  估计没空搭理这点小钱

2024-10-15 09:15 UTC, TLovers commented
> > > antdv3.2.20啥时候能发一版啊
> > 
> > 
> > 让唐老师亮出收款码吧，一人一点捐助下！我看下不知道理解的对不对，好像就是vue 的ts的命名空间改了导致一直失败
> 
> 哈哈哈 估计没空搭理这点小钱

算是开玩笑吧，其实3的存量应该非常多，本来就是开源的，也不能绑架唐老师。只能只要了。其实我想给这个贡献，但是又怕搞得不对，很纠结zzzz

2025-02-23 02:40 UTC, closed without merging