fix: fixed error with no expected value in `expandColumnTitle` slot
vueComponent/ant-design-vue pull request #7265
Opened 2024-01-10 17:23 UTC by cc-hearts

compatible with edge cases where the value of the `expandColumnTitle` slot is null

close #7260

2024-01-12 02:32 UTC, tangjinzhou commented
用的  renderSlot 的地方都有这个隐患吧，可以全局排查下

2024-01-12 03:43 UTC, cc-hearts commented
`renderSlot ` 似乎不是开放的 Api，是不是要考虑 使用默认的 jsx slot 的渲染方式去替换 `renderSlot ` 这个方法？如果可以，我全局都排查改下

2024-01-12 17:48 UTC, aibayanyu20 requested changes

2024-01-12 17:48 UTC, aibayanyu20 commented on components/vc-table/hooks/useColumns.tsx
> +import { customRenderSlot } from 'ant-design-vue/es/_util/vnode';
这里应该使用相对路径吧

2024-01-13 00:32 UTC, cc-hearts commented
done

2024-01-16 12:49 UTC, merged

2024-02-02 05:49 UTC, wsxe9988 commented
@cc-hearts 老哥，可以给3.x提个么

2024-02-02 06:05 UTC, cc-hearts commented
> @cc-hearts 老哥，可以给3.x提个么

已经有 3.x的pr了 。 #7252